import React, { useState, useRef } from 'react';
import { StyleSheet, Image, Dimensions } from 'react-native';
import Swiper from 'react-native-swiper';
import { View, Text, TouchableOpacity } from 'react-native';
import { PinchGestureHandler } from 'react-native-gesture-handler';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Icon from 'react-native-vector-icons/Ionicons';

Ionicons.loadFont().then();

const { width, height } = Dimensions.get('window');

const data = [
  // ...
  { title: 'مقدمة(English)', image: require('../assets/images/0.jpg'), music: require('../assets/music/0.jpg') },
  { title: 'مقدمة(Arabic)', image: require('../assets/images/1.jpg'), music: require('../assets/music/1.jpg') },
  { title: '1. إسم بتاو بركة يسو', image: require('../assets/images/001.jpg'), music: require('../assets/music/001.jpg') },
  { title: '2. بركة تا يسو خلي قيني', image: require('../assets/images/002.jpg'), music: require('../assets/music/002.jpg') },
  { title: '3. خلي نينا ياشباب', image: require('../assets/images/003.jpg'), music: require('../assets/music/003.jpg') },
  { title: '4. بركة انا ليقو', image: require('../assets/images/004.jpg'), music: require('../assets/music/004.jpg') },
  { title: '5. نينا ودي لربنا شكراً', image: require('../assets/images/005.jpg'), music: require('../assets/music/005.jpg') },
  { title: '6. شكراً شكراً يسو', image: require('../assets/images/006.jpg'), music: require('../assets/music/006.jpg') },
  { title: '7. ايه ايه شبابو شكرو ربنا', image: require('../assets/images/007.jpg'), music: require('../assets/music/007.jpg') },
  { title: '8. شكرو الله شكرو', image: require('../assets/images/008.jpg'), music: require('../assets/music/008.jpg') },
  { title: '9. بركة تا الله بيماشي طوالي', image: require('../assets/images/009.jpg'), music: require('../assets/music/009.jpg') },
  { title: '10. خلي شكورو إسم تا يسو', image: require('../assets/images/010.jpg'), music: require('../assets/music/010.jpg') },
  { title: '11. نينا حسا بشكورو الله آه آه آه', image: require('../assets/images/011.jpg'), music: require('../assets/music/011.jpg') },
  { title: '12. أنا بشكورو يسو', image: require('../assets/images/012.jpg'), music: require('../assets/music/012.jpg') },
  { title: '13. نينا كلو عيال تا الله', image: require('../assets/images/013.jpg'), music: require('../assets/music/013.jpg') },
  { title: '14. خلي نينا شكرو الله', image: require('../assets/images/014.jpg'), music: require('../assets/music/014.jpg') },
  { title: '15. الليلة يا أخوانا', image: require('../assets/images/015.jpg'), music: require('../assets/music/015.jpg') },
  { title: '16. ناسي اللي رودو يسو', image: require('../assets/images/016.jpg'), music: require('../assets/music/016.jpg') },
  { title: '17. اه يا أخوانا نينا ليقو حياة', image: require('../assets/images/017.jpg'), music: require('../assets/music/017.jpg') },
  { title: '18. في حياة في يسو مسيا', image: require('../assets/images/018.jpg'), music: require('../assets/music/018.jpg') },
  { title: '19. يسو بحبني', image: require('../assets/images/019.jpg'), music: require('../assets/music/019.jpg') },
  { title: '20. بنلموا مع ربي يسو', image: require('../assets/images/020.jpg'), music: require('../assets/music/020.jpg') },
  { title: '21. فرح تا ربنا دى قوة تايى', image: require('../assets/images/021.jpg'), music: require('../assets/music/021.jpg') },
  { title: '22. هللو هللو هللويا نينا غونا هللويا', image: require('../assets/images/022.jpg'), music: require('../assets/music/022.jpg') },
  { title: '23. انا ما ليقو إسم تاني', image: require('../assets/images/023.jpg'), music: require('../assets/music/023.jpg') },
  { title: '24. يسو دي حقي هو حقي للأبد', image: require('../assets/images/024.jpg'), music: require('../assets/music/024.jpg') },
  { title: '25. إفرحوا في الرب', image: require('../assets/images/025.jpg'), music: require('../assets/music/025.jpg') },
  { title: '26. عشان كويس تا الله', image: require('../assets/images/026.jpg'), music: require('../assets/music/026.jpg') },
  { title: '27. بركة تا ربنا بيقيني مع انا', image: require('../assets/images/027.jpg'), music: require('../assets/music/027.jpg') },
  { title: '28. كلو زول عاينو لانا', image: require('../assets/images/028.jpg'), music: require('../assets/music/028.jpg') },
  { title: '29. نورو قايد بولع', image: require('../assets/images/029.jpg'), music: require('../assets/music/029.jpg') },
  { title: '30. لو كاني يسو مافي', image: require('../assets/images/030.jpg'), music: require('../assets/music/030.jpg') },
  { title: '31. يوم تا الليلة', image: require('../assets/images/031.jpg'), music: require('../assets/music/031.jpg') },
  { title: '32. الله انت ياو الله في زمن كلو', image: require('../assets/images/032.jpg'), music: require('../assets/music/032.jpg') },
  { title: '33. حسا أنا عاريفو', image: require('../assets/images/033.jpg'), music: require('../assets/music/033.jpg') },
  { title: '34. مافي إله تاني زي يسو', image: require('../assets/images/034.jpg'), music: require('../assets/music/034.jpg') },
  { title: '35. دى منو بليمو ناسي', image: require('../assets/images/035.jpg'), music: require('../assets/music/035.jpg') },
  { title: '36. ربنا دي خلي مجدو', image: require('../assets/images/036.jpg'), music: require('../assets/music/036.jpg') },
  { title: '37. هو حي آمين', image: require('../assets/images/037.jpg'), music: require('../assets/music/037.jpg') },
  { title: '38. مافي حاجة بقاسي الله', image: require('../assets/images/038.jpg'), music: require('../assets/music/038.jpg') },
  { title: '39. يسو قـوة قـوة أعظم قـوة', image: require('../assets/images/039.jpg'), music: require('../assets/music/039.jpg') },
  { title: '40. بابا الفي السماء', image: require('../assets/images/040.jpg'), music: require('../assets/music/040.jpg') },
  { title: '41. ربنا أنت كبير', image: require('../assets/images/041.jpg'), music: require('../assets/music/041.jpg') },
  { title: '42. إسم بتو يسو', image: require('../assets/images/042.jpg'), music: require('../assets/music/042.jpg') },
  { title: '43. شبابو كلو تعالو نينا غونا', image: require('../assets/images/043.jpg'), music: require('../assets/music/043.jpg') },
  { title: '44. نورو بيولع نورو تا يسو', image: require('../assets/images/044.jpg'), music: require('../assets/music/044.jpg') },
  { title: '45. كان شوفتو يسوا هو بركة', image: require('../assets/images/045.jpg'), music: require('../assets/music/045.jpg') },
  { title: '46. كل زول بتال ربنا بيحبو', image: require('../assets/images/046.jpg'), music: require('../assets/music/046.jpg') },
  { title: '47. الله تايي الفي سماء', image: require('../assets/images/047.jpg'), music: require('../assets/music/047.jpg') },
  { title: '48. دى مونو مونو زى', image: require('../assets/images/048.jpg'), music: require('../assets/music/048.jpg') },
  { title: '49. يسو جبل تا دوسو تا ناسي', image: require('../assets/images/049.jpg'), music: require('../assets/music/049.jpg') },
  { title: '50. نينا ما بتاباني', image: require('../assets/images/050.jpg'), music: require('../assets/music/050.jpg') },
  { title: '51. هو عمل لي انا', image: require('../assets/images/051.jpg'), music: require('../assets/music/051.jpg') },
  { title: '52. يسو لنينا حياة', image: require('../assets/images/052.jpg'), music: require('../assets/music/052.jpg') },
  { title: '53. انت ياهو الله تايي', image: require('../assets/images/053.jpg'), music: require('../assets/music/053.jpg') },
  { title: '54. ياوي ياوي ياوي ياوي', image: require('../assets/images/054.jpg'), music: require('../assets/music/054.jpg') },
  { title: '55. الله خلقو دنيا', image: require('../assets/images/055.jpg'), music: require('../assets/music/055.jpg') },
  { title: '56. ربنا الله حبو دنيا', image: require('../assets/images/056.jpg'), music: require('../assets/music/056.jpg') },
  { title: '57. ربنا حبو اداما', image: require('../assets/images/057.jpg'), music: require('../assets/music/057.jpg') },
  { title: '58. بنعمة بنعيشوا', image: require('../assets/images/058.jpg'), music: require('../assets/music/058.jpg') },
  { title: '59. بابا الله رسلو النورو', image: require('../assets/images/059.jpg'), music: require('../assets/music/059.jpg') },
  { title: '60. ربنا كويسي', image: require('../assets/images/060.jpg'), music: require('../assets/music/060.jpg') },
  { title: '61. الله باركو باركو أنا', image: require('../assets/images/061.jpg'), music: require('../assets/music/061.jpg') },
  { title: '62. نينا عساكري سيي', image: require('../assets/images/062.jpg'), music: require('../assets/music/062.jpg') },
  { title: '63. في دنيا كلو فكري ربنا', image: require('../assets/images/063.jpg'), music: require('../assets/music/063.jpg') },
  { title: '64. وري سكة الماشي في سماء', image: require('../assets/images/064.jpg'), music: require('../assets/music/064.jpg') },
  { title: '65. ربنا رسلو يسو', image: require('../assets/images/065.jpg'), music: require('../assets/music/065.jpg') },
  { title: '66. يا أبوي تعالي ليسو', image: require('../assets/images/066.jpg'), music: require('../assets/music/066.jpg') },
  { title: '67. انا رسلكم هناك في عالم', image: require('../assets/images/067.jpg'), music: require('../assets/music/067.jpg') },
  { title: '68. اوه اوه يسو ساعدني', image: require('../assets/images/068.jpg'), music: require('../assets/music/068.jpg') },
  { title: '69. نينا شبابو كلو', image: require('../assets/images/069.jpg'), music: require('../assets/music/069.jpg') },
  { title: '70. مراسلا نينا كلو مراسلا', image: require('../assets/images/070.jpg'), music: require('../assets/music/070.jpg') },
  { title: '71. كلمة بتا يسو نادي انت', image: require('../assets/images/071.jpg'), music: require('../assets/music/071.jpg') },
  { title: '72. خلي نينا فتشو سكة', image: require('../assets/images/072.jpg'), music: require('../assets/music/072.jpg') },
  { title: '73. يسوا سابي الكويسي', image: require('../assets/images/073.jpg'), music: require('../assets/music/073.jpg') },
  { title: '74. كلو كلو كلو كلو', image: require('../assets/images/074.jpg'), music: require('../assets/music/074.jpg') },
  { title: '75. يسوا قوة بتاي', image: require('../assets/images/075.jpg'), music: require('../assets/music/075.jpg') },
  { title: '76. كاني شيطاني جيري', image: require('../assets/images/076.jpg'), music: require('../assets/music/076.jpg') },
  { title: '77. أنا بوقف قوي بقوة', image: require('../assets/images/077.jpg'), music: require('../assets/music/077.jpg') },
  { title: '78. إيماني إيماني', image: require('../assets/images/078.jpg'), music: require('../assets/music/078.jpg') },
  { title: '79. عندي إيمان', image: require('../assets/images/079.jpg'), music: require('../assets/music/079.jpg') },
  { title: '80. شيلو انا في ايدا يسوا', image: require('../assets/images/080.jpg'), music: require('../assets/music/080.jpg') },
  { title: '81. لي لي لي ياخوانا نينا بفكري', image: require('../assets/images/081.jpg'), music: require('../assets/music/081.jpg') },
  { title: '82. كلام تا ربنا وصلو ليونا', image: require('../assets/images/082.jpg'), music: require('../assets/music/082.jpg') },
  { title: '83. انا عاوزو أسمع كلام تا الله دى', image: require('../assets/images/083.jpg'), music: require('../assets/music/083.jpg') },
  { title: '84. نوا سالا بابورو', image: require('../assets/images/084.jpg'), music: require('../assets/music/084.jpg') },
  { title: '85. شاول هو قا بفكري', image: require('../assets/images/085.jpg'), music: require('../assets/music/085.jpg') },
  { title: '86. الله كلمو ليرميا', image: require('../assets/images/086.jpg'), music: require('../assets/music/086.jpg') },
  { title: '87. كفاية تايي', image: require('../assets/images/087.jpg'), music: require('../assets/music/087.jpg') },
  { title: '88. أسمع كلام تا الله', image: require('../assets/images/088.jpg'), music: require('../assets/music/088.jpg') },
  { title: '89. انت زولو بطالي', image: require('../assets/images/089.jpg'), music: require('../assets/music/089.jpg') },
  { title: '90. وخطياتي انا اعملو الله', image: require('../assets/images/090.jpg'), music: require('../assets/music/090.jpg') },
  { title: '91. أرفع إسم تا يسو', image: require('../assets/images/091.jpg'), music: require('../assets/music/091.jpg') },
  { title: '92. ربنا رسلو جنا يسو', image: require('../assets/images/092.jpg'), music: require('../assets/music/092.jpg') },
  { title: '93. إيدو فايدة بتاكي', image: require('../assets/images/093.jpg'), music: require('../assets/music/093.jpg') },
  { title: '94. خلي نينا بقى رودو يسوا', image: require('../assets/images/094.jpg'), music: require('../assets/music/094.jpg') },
  { title: '95. أنا ودورو في دنيا', image: require('../assets/images/095.jpg'), music: require('../assets/music/095.jpg') },
  { title: '96. إيليا النبي صلي لربنا', image: require('../assets/images/096.jpg'), music: require('../assets/music/096.jpg') },
  { title: '97. ربنا خطية بتاي بقى كتير', image: require('../assets/images/097.jpg'), music: require('../assets/music/097.jpg') },
  { title: '98. بدونك انت يسو أنا تعباني', image: require('../assets/images/098.jpg'), music: require('../assets/music/098.jpg') },
  { title: '99. اوه يا أخوانا خلي نينا', image: require('../assets/images/099.jpg'), music: require('../assets/music/099.jpg') },
  { title: '100. وري قوة تاكي يسو', image: require('../assets/images/100.jpg'), music: require('../assets/music/100.jpg') },
  { title: '101. باولو مع سيلا كان صلي', image: require('../assets/images/101.jpg'), music: require('../assets/music/101.jpg') },
  { title: '102. امسكو انا في ايدا يسو', image: require('../assets/images/102.jpg'), music: require('../assets/music/102.jpg') },
  { title: '103. اوه جريكو بلد كبير', image: require('../assets/images/103.jpg'), music: require('../assets/music/103.jpg') },
  { title: '104. يومو كبير بتا ربنا', image: require('../assets/images/104.jpg'), music: require('../assets/music/104.jpg') },
  { title: '105. في أخر يوم يسو', image: require('../assets/images/105.jpg'), music: require('../assets/music/105.jpg') },
  { title: '106. زول بتا دلع دلع بتا دنيا', image: require('../assets/images/106.jpg'), music: require('../assets/music/106.jpg') },
  { title: '107. يسو ملك في سماء', image: require('../assets/images/107.jpg'), music: require('../assets/music/107.jpg') },
  { title: '108. يومو قريبو يسوا بريجا', image: require('../assets/images/108.jpg'), music: require('../assets/music/108.jpg') },
  { title: '109. مونو بريجا تاني', image: require('../assets/images/109.jpg'), music: require('../assets/music/109.jpg') },
  { title: '110. سيي يسو بريجا', image: require('../assets/images/110.jpg'), music: require('../assets/music/110.jpg') },
  { title: '111. بيت تا ابوي ألفي سماء', image: require('../assets/images/111.jpg'), music: require('../assets/music/111.jpg') },
  { title: '112. تورومبيتا تورومبيتا بكوري', image: require('../assets/images/112.jpg'), music: require('../assets/music/112.jpg') },
  { title: '113. تورمبيتا بكوري', image: require('../assets/images/113.jpg'), music: require('../assets/music/113.jpg') },
  { title: '114. انت ربي ابو تا نينا', image: require('../assets/images/114.jpg'), music: require('../assets/music/114.jpg') },
  { title: '115. نينا عيال عيال تا ربنا', image: require('../assets/images/115.jpg'), music: require('../assets/music/115.jpg') },
  { title: '116. اورشليم مدينة بتا ربنا', image: require('../assets/images/116.jpg'), music: require('../assets/music/116.jpg') },
  { title: '117. هناك في سماء', image: require('../assets/images/117.jpg'), music: require('../assets/music/117.jpg') },
  { title: '118. بركة كويسي', image: require('../assets/images/118.jpg'), music: require('../assets/music/118.jpg') },
  { title: '119. شوفو الدنيا ملا مع خطية', image: require('../assets/images/119.jpg'), music: require('../assets/music/119.jpg') },
  { title: '120. ربنا جيبو لنينا جنا يسو', image: require('../assets/images/120.jpg'), music: require('../assets/music/120.jpg') },
  { title: '121. يسو موتو في الصليب', image: require('../assets/images/121.jpg'), music: require('../assets/music/121.jpg') },
  { title: '122. ربنا رسلو يسو', image: require('../assets/images/122.jpg'), music: require('../assets/music/122.jpg') },
  { title: '123. ربنا الليلة بحبو نينا كلو', image: require('../assets/images/123.jpg'), music: require('../assets/music/123.jpg') },
  { title: '124. سكة تا سماء الحقيقة', image: require('../assets/images/124.jpg'), music: require('../assets/music/124.jpg') },
  { title: '125. يسو سكة تا سماء', image: require('../assets/images/125.jpg'), music: require('../assets/music/125.jpg') },
  { title: '126. شنو كاسلو انا', image: require('../assets/images/126.jpg'), music: require('../assets/music/126.jpg') },
  { title: '127. سكة تا سماء هو يسو', image: require('../assets/images/127.jpg'), music: require('../assets/music/127.jpg') },
  { title: '128. يسو موتو فوق هناك', image: require('../assets/images/128.jpg'), music: require('../assets/music/128.jpg') },
  { title: '129. دمو تا يسو', image: require('../assets/images/129.jpg'), music: require('../assets/music/129.jpg') },
  { title: '130. هو حقي هو حقي', image: require('../assets/images/130.jpg'), music: require('../assets/music/130.jpg') },
  { title: '131. هللويا  نينا عيال تا الله', image: require('../assets/images/131.jpg'), music: require('../assets/music/131.jpg') },
  { title: '132. نقيت مافي بتا سواتا', image: require('../assets/images/132.jpg'), music: require('../assets/music/132.jpg') },
  { title: '133. دنيا دي بطال عندو كلام كتير', image: require('../assets/images/133.jpg'), music: require('../assets/music/133.jpg') },
  { title: '134. انا ما بيليقو معنى تا حياة', image: require('../assets/images/134.jpg'), music: require('../assets/music/134.jpg') },
  { title: '135. أنا ودي ليسو حياة', image: require('../assets/images/135.jpg'), music: require('../assets/music/135.jpg') },
  { title: '136. خلي نينا ودي شكراً لالله', image: require('../assets/images/136.jpg'), music: require('../assets/music/136.jpg') },
  { title: '137. خلي نينا ياشباب', image: require('../assets/images/137.jpg'), music: require('../assets/music/137.jpg') },
  { title: '138. هو حبوا أنا', image: require('../assets/images/138.jpg'), music: require('../assets/music/138.jpg') },
  { title: '139. حياة بتاي كلو ليسو', image: require('../assets/images/139.jpg'), music: require('../assets/music/139.jpg') },
  { title: '140. جنا تا داودي هو سولومونا', image: require('../assets/images/140.jpg'), music: require('../assets/music/140.jpg') },
  { title: '141. حفظو كنيسة', image: require('../assets/images/141.jpg'), music: require('../assets/music/141.jpg') },
  { title: '142. يا أخوانا في مسيا', image: require('../assets/images/142.jpg'), music: require('../assets/music/142.jpg') },
  { title: '143. تعالي نينا ليمو في جوا كنيسة', image: require('../assets/images/143.jpg'), music: require('../assets/music/143.jpg') },
  { title: '144. نينا ليمو الليلة دي', image: require('../assets/images/144.jpg'), music: require('../assets/music/144.jpg') },
  { title: '145. ربنا كلمو لبابا ابراما', image: require('../assets/images/145.jpg'), music: require('../assets/music/145.jpg') },
  { title: '146. حنانيا و سفيرة', image: require('../assets/images/146.jpg'), music: require('../assets/music/146.jpg') },
  { title: '147. يا اخوانا ودي لي الله', image: require('../assets/images/147.jpg'), music: require('../assets/music/147.jpg') },
  { title: '148. دورو مع يسو', image: require('../assets/images/148.jpg'), music: require('../assets/music/148.jpg') },
  { title: '149. في بداية الله كلم', image: require('../assets/images/149.jpg'), music: require('../assets/music/149.jpg') },
  { title: '150. يسوا ليقو تعبو', image: require('../assets/images/150.jpg'), music: require('../assets/music/150.jpg') },
  { title: '151. ناسي ابا يسوا', image: require('../assets/images/151.jpg'), music: require('../assets/music/151.jpg') },
  { title: '152. ناسي تعبو يسو', image: require('../assets/images/152.jpg'), music: require('../assets/music/152.jpg') },
  { title: '153. يسو جنا ربنا موتو', image: require('../assets/images/153.jpg'), music: require('../assets/music/153.jpg') },
  { title: '154. هللويا يسو حي', image: require('../assets/images/154.jpg'), music: require('../assets/music/154.jpg') },
  { title: '155. ربنا كان شوفو', image: require('../assets/images/155.jpg'), music: require('../assets/music/155.jpg') },
  { title: '156. انا عندو سابي', image: require('../assets/images/156.jpg'), music: require('../assets/music/156.jpg') },
  { title: '157. ربنا قالي نوا سالا بابورو', image: require('../assets/images/157.jpg'), music: require('../assets/music/157.jpg') },
  { title: '158. ناسي كلو فكري ماريا', image: require('../assets/images/158.jpg'), music: require('../assets/music/158.jpg') },
  { title: '159. زول بتا جدامو كبير تا جيشي', image: require('../assets/images/159.jpg'), music: require('../assets/music/159.jpg') },
  { title: '160. دنيا دي ملا مع كلام', image: require('../assets/images/160.jpg'), music: require('../assets/music/160.jpg') },
  { title: '161. خلي يسوا قيني جوة', image: require('../assets/images/161.jpg'), music: require('../assets/music/161.jpg') },
  { title: '162. داودي كاني كوري', image: require('../assets/images/162.jpg'), music: require('../assets/music/162.jpg') },
  { title: '163. في ساعة بتا نوا دنيا كلو', image: require('../assets/images/163.jpg'), music: require('../assets/music/163.jpg') },
  { title: '164. ربنا حافظ عيال تاكي', image: require('../assets/images/164.jpg'), music: require('../assets/music/164.jpg') },
  { title: '165. دة معيشة ياتو البكبسو انا', image: require('../assets/images/165.jpg'), music: require('../assets/music/165.jpg') },
  { title: '166. الله وري نينا سكة', image: require('../assets/images/166.jpg'), music: require('../assets/music/166.jpg') },
  { title: '167. فكري حبو بتا ربنا', image: require('../assets/images/167.jpg'), music: require('../assets/music/167.jpg') },
  { title: '168. شيطان خلي ورا', image: require('../assets/images/168.jpg'), music: require('../assets/music/168.jpg') },
  { title: '169. يسو مسيا حبو نينا', image: require('../assets/images/169.jpg'), music: require('../assets/music/169.jpg') },
  { title: '170. يا سابي دنيا دى تا منو', image: require('../assets/images/170.jpg'), music: require('../assets/music/170.jpg') },
  { title: '171. انتم يا ناسي تا دنيا دي', image: require('../assets/images/171.jpg'), music: require('../assets/music/171.jpg') },
  { title: '172. يا بابا يا ماما تالي', image: require('../assets/images/172.jpg'), music: require('../assets/music/172.jpg') },
  { title: '173. يسو هو شوفو انا الليلة', image: require('../assets/images/173.jpg'), music: require('../assets/music/173.jpg') },
  { title: '174. انا كنت جنا الودورو', image: require('../assets/images/174.jpg'), music: require('../assets/music/174.jpg') },
  { title: '175. انا ما عزو كلام بتا خطية', image: require('../assets/images/175.jpg'), music: require('../assets/music/175.jpg') },
  { title: '176. انا ليسة عميان تعال', image: require('../assets/images/176.jpg'), music: require('../assets/music/176.jpg') },
  { title: '177. إلا يسو ياو بتيمو', image: require('../assets/images/177.jpg'), music: require('../assets/music/177.jpg') },
  { title: '178. نسية يا اخوانا ربنا', image: require('../assets/images/178.jpg'), music: require('../assets/music/178.jpg') },
  { title: '179. نينا وصلو في سنة جديد', image: require('../assets/images/179.jpg'), music: require('../assets/music/179.jpg') },
  { title: '180. سابى تانى مافيش حق زى يسو', image: require('../assets/images/180.jpg'), music: require('../assets/music/180.jpg') },
  { title: '181. رودو يسو كريستو', image: require('../assets/images/181.jpg'), music: require('../assets/music/181.jpg') },
  { title: '182. ساعدني يسو', image: require('../assets/images/182.jpg'), music: require('../assets/music/182.jpg') },
  { title: '183. الليلة دي فرحة كبير', image: require('../assets/images/183.jpg'), music: require('../assets/music/183.jpg') },
  { title: '184. ولدو يسو المسيا', image: require('../assets/images/184.jpg'), music: require('../assets/music/184.jpg') },
  { title: '185. يوسفو و مريامو', image: require('../assets/images/185.jpg'), music: require('../assets/music/185.jpg') },
  { title: '186. في بيت لحم يهود', image: require('../assets/images/186.jpg'), music: require('../assets/music/186.jpg') },
  { title: '187. ولدو يسو في بيت لحم', image: require('../assets/images/187.jpg'), music: require('../assets/music/187.jpg') },
  { title: '188. بعدي ماريامو ولدو يسو', image: require('../assets/images/188.jpg'), music: require('../assets/music/188.jpg') },
  { title: '189. يوم تا فرح جدا', image: require('../assets/images/189.jpg'), music: require('../assets/music/189.jpg') },
  { title: '190. ماريا ولدو لنينا يسوا', image: require('../assets/images/190.jpg'), music: require('../assets/music/190.jpg') },
  { title: '191. بابا مسيا الله', image: require('../assets/images/191.jpg'), music: require('../assets/music/191.jpg') },
  { title: '192. ولدو بتا يسو مسيا', image: require('../assets/images/192.jpg'), music: require('../assets/music/192.jpg') },
  { title: '193. احلى منك وين القى', image: require('../assets/images/193.jpg'), music: require('../assets/music/193.jpg') },
  { title: '194. نحنا جايين ليك', image: require('../assets/images/194.jpg'), music: require('../assets/music/194.jpg') },
  { title: '195. حنغني ليك ياملك الشعوب', image: require('../assets/images/195.jpg'), music: require('../assets/music/195.jpg') },
  { title: '196. حنغني ليك يا حبيبنا', image: require('../assets/images/196.jpg'), music: require('../assets/music/196.jpg') },
  { title: '197. ده سلام ده سلام عجيب', image: require('../assets/images/197.jpg'), music: require('../assets/music/197.jpg') },
  { title: '198. دي حياة جديدة بفضل ربي', image: require('../assets/images/198.jpg'), music: require('../assets/music/198.jpg') },
  { title: '199. لما ارجع بس واعاين', image: require('../assets/images/199.jpg'), music: require('../assets/music/199.jpg') },
  { title: '200. نحنا جايين ليك', image: require('../assets/images/200.jpg'), music: require('../assets/music/200.jpg') },
  { title: '201. يا قلبي ليك كل الفرح', image: require('../assets/images/201.jpg'), music: require('../assets/music/201.jpg') },
  { title: '202.كم سنة مرت من عمري ', image: require('../assets/images/202.jpg'), music: require('../assets/music/202.jpg') },
  { title: '203. ملك الملوك بنسبحك', image: require('../assets/images/203.jpg'), music: require('../assets/music/203.jpg') },
  { title: '204. أنت سيد الكون', image: require('../assets/images/204.jpg'), music: require('../assets/music/204.jpg') },
  { title: '205. رسمتك في الجبين عنوان', image: require('../assets/images/205.jpg'), music: require('../assets/music/205.jpg') },
  { title: '206. كل الشعوب في قدسك', image: require('../assets/images/206.jpg'), music: require('../assets/music/206.jpg') },
  { title: '207. انت اسمى من الغنى', image: require('../assets/images/207.jpg'), music: require('../assets/music/207.jpg') },
  { title: '208. برتاح في حضنك', image: require('../assets/images/208.jpg'), music: require('../assets/music/208.jpg') },
  { title: '209. بسمع الاذن سمعت يا ربي', image: require('../assets/images/209.jpg'), music: require('../assets/music/209.jpg') },
  { title: '210. ليك ياربي يعلو أحلى نشيد', image: require('../assets/images/210.jpg'), music: require('../assets/music/210.jpg') },
  { title: '211. من القليب طلع النشيد', image: require('../assets/images/211.jpg'), music: require('../assets/music/211.jpg') },
  { title: '212. منو زيك انت', image: require('../assets/images/212.jpg'), music: require('../assets/music/212.jpg') },
  { title: '213. يا الله أنت الاله المستحق', image: require('../assets/images/213.jpg'), music: require('../assets/music/213.jpg') },
  { title: '214. بنزف عريسنا في هيكله', image: require('../assets/images/214.jpg'), music: require('../assets/music/214.jpg') },
  { title: '215. بنجيك يارب الكون', image: require('../assets/images/215.jpg'), music: require('../assets/music/215.jpg') },
  { title: '216. بيه بتفرح السموات', image: require('../assets/images/216.jpg'), music: require('../assets/music/216.jpg') },
  { title: '217. تسبيحنا وتصفيقنا', image: require('../assets/images/217.jpg'), music: require('../assets/music/217.jpg') },
  { title: '218. جوه قليبي برنم ليسوعي', image: require('../assets/images/218.jpg'), music: require('../assets/music/218.jpg') },
  { title: '219. ربي يااعظم اله', image: require('../assets/images/219.jpg'), music: require('../assets/music/219.jpg') },
  { title: '220. عظمت العمل معنا', image: require('../assets/images/220.jpg'), music: require('../assets/music/220.jpg') },
  { title: '221. رب الوجود اسمك عظيم', image: require('../assets/images/221.jpg'), music: require('../assets/music/221.jpg') },
  { title: '222. علمني اعيش ابشر بحبك', image: require('../assets/images/222.jpg'), music: require('../assets/music/222.jpg') },
  { title: '223. ما خسارة انك مت', image: require('../assets/images/223.jpg'), music: require('../assets/music/223.jpg') },
  { title: '224. مافي مثلك مافي مثلك', image: require('../assets/images/224.jpg'), music: require('../assets/music/224.jpg') },
  { title: '225. مجدا ليك يا يسوعنا', image: require('../assets/images/225.jpg'), music: require('../assets/music/225.jpg') },
  { title: '226. نبض الحروف تتلاشى', image: require('../assets/images/226.jpg'), music: require('../assets/music/226.jpg') },
  { title: '227. يسوعي بسبح ليك', image: require('../assets/images/227.jpg'), music: require('../assets/music/227.jpg') },
  { title: '228. ربي عن حبك بقول', image: require('../assets/images/228.jpg'), music: require('../assets/music/228.jpg') },
  { title: '229. المحبة المحبة', image: require('../assets/images/229.jpg'), music: require('../assets/music/229.jpg') },
  { title: '230. احباب الله انحنا', image: require('../assets/images/230.jpg'), music: require('../assets/music/230.jpg') },
  { title: '231. منو متلك دايماً قليبه حنون', image: require('../assets/images/231.jpg'), music: require('../assets/music/231.jpg') },
  { title: '232. جوه الهنا قلب حنون', image: require('../assets/images/232.jpg'), music: require('../assets/music/232.jpg') },
  { title: '233. واحد في حياتي بحبه', image: require('../assets/images/233.jpg'), music: require('../assets/music/233.jpg') },
  { title: '234. يا ربي بحبك كلمة', image: require('../assets/images/234.jpg'), music: require('../assets/music/234.jpg') },
  { title: '235. يا هنايا بيسوعي', image: require('../assets/images/235.jpg'), music: require('../assets/music/235.jpg') },
  { title: '236. يا مسيحنا انت لينا', image: require('../assets/images/236.jpg'), music: require('../assets/music/236.jpg') },
  { title: '237. اصـوغ الحروف', image: require('../assets/images/237.jpg'), music: require('../assets/music/237.jpg') },
  { title: '238. لابالصدفة خلقتني', image: require('../assets/images/238.jpg'), music: require('../assets/music/238.jpg') },
  { title: '239. لولاك ما عرفت الطريق', image: require('../assets/images/239.jpg'), music: require('../assets/music/239.jpg') },
  { title: '240. لما تغشانا المواجع', image: require('../assets/images/240.jpg'), music: require('../assets/music/240.jpg') },
  { title: '241. لما بكيت والدمع سال', image: require('../assets/images/241.jpg'), music: require('../assets/music/241.jpg') },
  { title: '242. منو غيرك بيرحمنا', image: require('../assets/images/242.jpg'), music: require('../assets/music/242.jpg') },
  { title: '243. من قلب انسان بعرفك', image: require('../assets/images/243.jpg'), music: require('../assets/music/243.jpg') },
  { title: '244. نزلت من علاك', image: require('../assets/images/244.jpg'), music: require('../assets/music/244.jpg') },
  { title: '245. يقوقي القمري شان', image: require('../assets/images/245.jpg'), music: require('../assets/music/245.jpg') },
  { title: '246. الليلة جيت شايل فرح', image: require('../assets/images/246.jpg'), music: require('../assets/music/246.jpg') },
  { title: '247. إحنا بالانجيل لقينا خلاص', image: require('../assets/images/247.jpg'), music: require('../assets/music/247.jpg') },
  { title: '248. الله قال بالدف نرنم', image: require('../assets/images/248.jpg'), music: require('../assets/music/248.jpg') },
  { title: '249. يسوع ساكن جوه قليبي', image: require('../assets/images/249.jpg'), music: require('../assets/music/249.jpg') },
  { title: '250. خاطئ وراجع راجع من بعـيد', image: require('../assets/images/250.jpg'), music: require('../assets/music/250.jpg') },
  { title: '251. جاييك أنا جاي وراجع', image: require('../assets/images/251.jpg'), music: require('../assets/music/251.jpg') },
  { title: '252. داير أكون معاك', image: require('../assets/images/252.jpg'), music: require('../assets/music/252.jpg') },
  { title: '253. من اعماق قلبي', image: require('../assets/images/253.jpg'), music: require('../assets/music/253.jpg') },
  { title: '254. وقتين اشوف', image: require('../assets/images/254.jpg'), music: require('../assets/music/254.jpg') },
  { title: '255. وقفنا عليك', image: require('../assets/images/255.jpg'), music: require('../assets/music/255.jpg') },
  { title: '256. ياربي شوف حالي', image: require('../assets/images/256.jpg'), music: require('../assets/music/256.jpg') },
  { title: '257. يارب الوجود', image: require('../assets/images/257.jpg'), music: require('../assets/music/257.jpg') },
  { title: '258. يا جمال دنيا أنت سلطانا', image: require('../assets/images/258.jpg'), music: require('../assets/music/258.jpg') },
  { title: '259. ياربي طالب حنك علي', image: require('../assets/images/259.jpg'), music: require('../assets/music/259.jpg') },
  { title: '260. يا ربي هاك باقي العمر', image: require('../assets/images/260.jpg'), music: require('../assets/music/260.jpg') },
  { title: '261. يا ربي شوف حالي', image: require('../assets/images/261.jpg'), music: require('../assets/music/261.jpg') },
  { title: '262. يأسان ذليل الحال', image: require('../assets/images/262.jpg'), music: require('../assets/music/262.jpg') },
  { title: '263. انا محتاجك يايسوع', image: require('../assets/images/263.jpg'), music: require('../assets/music/263.jpg') },
  { title: '264. ليك جايين يسوع', image: require('../assets/images/264.jpg'), music: require('../assets/music/264.jpg') },
  { title: '265. ربي بجيك بعد شتات', image: require('../assets/images/265.jpg'), music: require('../assets/music/265.jpg') },
  { title: '266. الصوت الفوق بينادي', image: require('../assets/images/266.jpg'), music: require('../assets/music/266.jpg') },
  { title: '267. خلاص قبلت المسيح', image: require('../assets/images/267.jpg'), music: require('../assets/music/267.jpg') },
  { title: '268. يسوع فداني غسل كياني', image: require('../assets/images/268.jpg'), music: require('../assets/music/268.jpg') },
  { title: '269. خلاص خلاص خلاص', image: require('../assets/images/269.jpg'), music: require('../assets/music/269.jpg') },
  { title: '270. زغرودة جات شقت', image: require('../assets/images/270.jpg'), music: require('../assets/music/270.jpg') },
  { title: '271. عريسنا جاي هو المسيح', image: require('../assets/images/271.jpg'), music: require('../assets/music/271.jpg') },
  { title: '272. غالية غالية', image: require('../assets/images/272.jpg'), music: require('../assets/music/272.jpg') },
  { title: '273. لا ماشي جنة ولا نار', image: require('../assets/images/273.jpg'), music: require('../assets/music/273.jpg') },
  { title: '274. متين ترجع راجينك يارب', image: require('../assets/images/274.jpg'), music: require('../assets/music/274.jpg') },
  { title: '275. نفسي قد تاقت إليك يسوعي', image: require('../assets/images/275.jpg'), music: require('../assets/music/275.jpg') },
  { title: '276. يا ريت يجي ياخدنا', image: require('../assets/images/276.jpg'), music: require('../assets/music/276.jpg') },
  { title: '277. يا عروسة حلوة', image: require('../assets/images/277.jpg'), music: require('../assets/music/277.jpg') },
  { title: '278. إنت إنت أبرع جمال', image: require('../assets/images/278.jpg'), music: require('../assets/music/278.jpg') },
  { title: '279. يا كنيسة يا عروسة المسيح', image: require('../assets/images/279.jpg'), music: require('../assets/music/279.jpg') },
  { title: '280. سوف ينتهي العذاب', image: require('../assets/images/280.jpg'), music: require('../assets/music/280.jpg') },
  { title: '281. أمسك كلامك في المسيح', image: require('../assets/images/281.jpg'), music: require('../assets/music/281.jpg') },
  { title: '282. خدعوني يا ربي يسوع', image: require('../assets/images/282.jpg'), music: require('../assets/music/282.jpg') },
  { title: '283. احنا بالانجيل لقينا خلاص', image: require('../assets/images/283.jpg'), music: require('../assets/music/283.jpg') },
  { title: '284. بنحكي الليلة قصة حب', image: require('../assets/images/284.jpg'), music: require('../assets/music/284.jpg') },
  { title: '285. سألوني الناس عن حبيبي', image: require('../assets/images/285.jpg'), music: require('../assets/music/285.jpg') },
  { title: '286. سألوني قالوا لي', image: require('../assets/images/286.jpg'), music: require('../assets/music/286.jpg') },
  { title: '287. عشان حبك لي يايسوع', image: require('../assets/images/287.jpg'), music: require('../assets/music/287.jpg') },
  { title: '288. فرحان بيسوع', image: require('../assets/images/288.jpg'), music: require('../assets/music/288.jpg') },
  { title: '289. اسأل نفسك تأني اسأل', image: require('../assets/images/289.jpg'), music: require('../assets/music/289.jpg') },
  { title: '290. ارجع تعال يااخوي', image: require('../assets/images/290.jpg'), music: require('../assets/music/290.jpg') },
  { title: '291. انت ليه يا زول بترفض', image: require('../assets/images/291.jpg'), music: require('../assets/music/291.jpg') },
  { title: '292. حيجئ يوم تعرف مصيرك', image: require('../assets/images/292.jpg'), music: require('../assets/music/292.jpg') },
  { title: '293. رسالة من بعيد', image: require('../assets/images/293.jpg'), music: require('../assets/music/293.jpg') },
  { title: '294. سيب الدنيا وتعال للمسيح', image: require('../assets/images/294.jpg'), music: require('../assets/music/294.jpg') },
  { title: '295. كيف اكون انا غيرك انت', image: require('../assets/images/295.jpg'), music: require('../assets/music/295.jpg') },
  { title: '296. ياناس تعالوا تلقوا السعادة', image: require('../assets/images/296.jpg'), music: require('../assets/music/296.jpg') },
  { title: '297. لو انت داير تروي', image: require('../assets/images/297.jpg'), music: require('../assets/music/297.jpg') },
  { title: '298. يا تائه ماشي النار', image: require('../assets/images/298.jpg'), music: require('../assets/music/298.jpg') },
  { title: '299. يا ماشي وما عارف لوين', image: require('../assets/images/299.jpg'), music: require('../assets/music/299.jpg') },
  { title: '300. ياخاطئ تعال ارح', image: require('../assets/images/300.jpg'), music: require('../assets/music/300.jpg') },
  { title: '301. يسوع هو سكة تا دنيا', image: require('../assets/images/301.jpg'), music: require('../assets/music/301.jpg') },
  { title: '302. انا الموعود', image: require('../assets/images/302.jpg'), music: require('../assets/music/302.jpg') },
  { title: '303. أنا متأكد ماشي للسماء', image: require('../assets/images/303.jpg'), music: require('../assets/music/303.jpg') },
  { title: '304. الليلة يوم عظيم', image: require('../assets/images/304.jpg'), music: require('../assets/music/304.jpg') },
  { title: '305. مبروك مبروك الرب اختاركم', image: require('../assets/images/305.jpg'), music: require('../assets/music/305.jpg') },
  { title: '306. انا للعريس بجملتي', image: require('../assets/images/306.jpg'), music: require('../assets/music/306.jpg') },
  { title: '307. سمحة سمحة', image: require('../assets/images/307.jpg'), music: require('../assets/music/307.jpg') },
  { title: '308. كانت البداية', image: require('../assets/images/308.jpg'), music: require('../assets/music/308.jpg') },
  { title: '309. كانوا اثنين في البداية', image: require('../assets/images/309.jpg'), music: require('../assets/music/309.jpg') },
  { title: '310. انا لسة حافظ الوصية', image: require('../assets/images/310.jpg'), music: require('../assets/music/310.jpg') },
  { title: '311. قلبي ليك يا العارف القلوب', image: require('../assets/images/311.jpg'), music: require('../assets/music/311.jpg') },
  { title: '312. قلبي هاك املك', image: require('../assets/images/312.jpg'), music: require('../assets/music/312.jpg') },
  { title: '313. لمن اقوم أنا بدري من نومي', image: require('../assets/images/313.jpg'), music: require('../assets/music/313.jpg') },
  { title: '314. نفسي عطشانة', image: require('../assets/images/314.jpg'), music: require('../assets/music/314.jpg') },
  { title: '315. يا الهي يا حبيبي يا يسوعـي', image: require('../assets/images/315.jpg'), music: require('../assets/music/315.jpg') },
  { title: '316. قصتي تبدأ معاك', image: require('../assets/images/316.jpg'), music: require('../assets/music/316.jpg') },
  { title: '317. جيت بامانة', image: require('../assets/images/317.jpg'), music: require('../assets/music/317.jpg') },
  { title: '318. انت يابلدي عزه ياسودان', image: require('../assets/images/318.jpg'), music: require('../assets/music/318.jpg') },
  { title: '319. يا الهنا فيض بروحك في بلدنا', image: require('../assets/images/319.jpg'), music: require('../assets/music/319.jpg') },
  { title: '320. ربي جينا ليك', image: require('../assets/images/320.jpg'), music: require('../assets/music/320.jpg') },
  { title: '321. قام ربي قام', image: require('../assets/images/321.jpg'), music: require('../assets/music/321.jpg') },
  { title: '322. لمن أنت قمت كان الانتصار', image: require('../assets/images/322.jpg'), music: require('../assets/music/322.jpg') },
  { title: '323. يوم خلاص تم الوقت', image: require('../assets/images/323.jpg'), music: require('../assets/music/323.jpg') },
  { title: '324. يد الرب ما قصرت', image: require('../assets/images/324.jpg'), music: require('../assets/music/324.jpg') },
  { title: '325. خلاص يا دنيا قبلت يسوع', image: require('../assets/images/325.jpg'), music: require('../assets/music/325.jpg') },
  { title: '326. جايك يسوع', image: require('../assets/images/326.jpg'), music: require('../assets/music/326.jpg') },
  { title: '327. ربي شال كل الهموم', image: require('../assets/images/327.jpg'), music: require('../assets/music/327.jpg') },
  { title: '328. ربي ليك كل العبادة', image: require('../assets/images/328.jpg'), music: require('../assets/music/328.jpg') },
  { title: '329. كله خاوي الا انت ربي', image: require('../assets/images/329.jpg'), music: require('../assets/music/329.jpg') },
  { title: '330. سنين ضاعت من عمري', image: require('../assets/images/330.jpg'), music: require('../assets/music/330.jpg') },
  { title: '331. رحلة رجوع خطوات اسف', image: require('../assets/images/331.jpg'), music: require('../assets/music/331.jpg') },
  { title: '332. إبليس مغلوب', image: require('../assets/images/332.jpg'), music: require('../assets/music/332.jpg') },
  { title: '333. لما تحصرني المخاطر', image: require('../assets/images/333.jpg'), music: require('../assets/music/333.jpg') },
  { title: '334. مشوار طويل', image: require('../assets/images/334.jpg'), music: require('../assets/music/334.jpg') },
  { title: '335. أنا برفع فوق', image: require('../assets/images/335.jpg'), music: require('../assets/music/335.jpg') },
  { title: '336. معاك معاك', image: require('../assets/images/336.jpg'), music: require('../assets/music/336.jpg') },
  { title: '337. معاك انا ما برجع', image: require('../assets/images/337.jpg'), music: require('../assets/music/337.jpg') },
  { title: '338. مع يسوع انا ما بخاف', image: require('../assets/images/338.jpg'), music: require('../assets/music/338.jpg') },
  { title: '339. انا انسان ضعيف', image: require('../assets/images/339.jpg'), music: require('../assets/music/339.jpg') },
  { title: '340. الهنا نور الكون الهنا', image: require('../assets/images/340.jpg'), music: require('../assets/music/340.jpg') },
  { title: '341. تعال اكلمك عن الحاميني', image: require('../assets/images/341.jpg'), music: require('../assets/music/341.jpg') },
  { title: '342. بلاقيك في الضياع', image: require('../assets/images/342.jpg'), music: require('../assets/music/342.jpg') },
  { title: '343. إحنا ماضلينا تهنا', image: require('../assets/images/343.jpg'), music: require('../assets/music/343.jpg') },
  { title: '344. ودع ظلام الماضي', image: require('../assets/images/344.jpg'), music: require('../assets/music/344.jpg') },
  { title: '345. وكتين اكون براي', image: require('../assets/images/345.jpg'), music: require('../assets/music/345.jpg') },
  { title: '346. تعال اكلمك عن الحاميني', image: require('../assets/images/346.jpg'), music: require('../assets/music/346.jpg') },
  { title: '347. يا نفسي كيف كيف تشتكي', image: require('../assets/images/347.jpg'), music: require('../assets/music/347.jpg') },
  { title: '348. انا ما بعيش الامعاك', image: require('../assets/images/348.jpg'), music: require('../assets/music/348.jpg') },
  { title: '349. بعرفك ياحبيب العمر', image: require('../assets/images/349.jpg'), music: require('../assets/music/349.jpg') },
  { title: '350. حن تعال شكل حياتي', image: require('../assets/images/350.jpg'), music: require('../assets/music/350.jpg') },
  { title: '351. جينا نطلب يا رب وجودك', image: require('../assets/images/351.jpg'), music: require('../assets/music/351.jpg') },
  { title: '352. وعودك صادقة لي يارب', image: require('../assets/images/352.jpg'), music: require('../assets/music/352.jpg') },
  { title: '353. افرحوا الليلة يومنا', image: require('../assets/images/353.jpg'), music: require('../assets/music/353.jpg') },
  { title: '354. جينا ليك يايسوعنا تاني', image: require('../assets/images/354.jpg'), music: require('../assets/music/354.jpg') },
  { title: '355. دق الجرس دق الجرس', image: require('../assets/images/355.jpg'), music: require('../assets/music/355.jpg') },
  { title: '356. عيد يسوع من تاني جانا', image: require('../assets/images/356.jpg'), music: require('../assets/music/356.jpg') },
  { title: '357. في ليلة الميلاد جاء الملاك', image: require('../assets/images/357.jpg'), music: require('../assets/music/357.jpg') },
  { title: '358. لما يسوع جاء في دنيانا', image: require('../assets/images/358.jpg'), music: require('../assets/music/358.jpg') },
  { title: '359. ذلك الشخص الذي', image: require('../assets/images/359.jpg'), music: require('../assets/music/359.jpg') },
  { title: '360. يا جنى المزود يا يسوعنا', image: require('../assets/images/360.jpg'), music: require('../assets/music/360.jpg') },
  { title: '361. يا طيور طيري', image: require('../assets/images/361.jpg'), music: require('../assets/music/361.jpg') },
  { title: '362. قدوس قدوس', image: require('../assets/images/362.jpg'), music: require('../assets/music/362.jpg') },
  { title: '363. أهديك كل المجد', image: require('../assets/images/363.jpg'), music: require('../assets/music/363.jpg') },
  { title: '364. أبانا نحبك نسجد ونعبدك', image: require('../assets/images/364.jpg'), music: require('../assets/music/364.jpg') },
  { title: '365. صممت أني اتبع يسوع', image: require('../assets/images/365.jpg'), music: require('../assets/music/365.jpg') },
  { title: '366. أنت عظيم', image: require('../assets/images/366.jpg'), music: require('../assets/music/366.jpg') },
  { title: '367. نرفعك فوق الجميع', image: require('../assets/images/367.jpg'), music: require('../assets/music/367.jpg') },
  { title: '368. رحمتك أفضل من الحياة', image: require('../assets/images/368.jpg'), music: require('../assets/music/368.jpg') },
  { title: '369. أيها السيد', image: require('../assets/images/369.jpg'), music: require('../assets/music/369.jpg') },
  { title: '370. نأتي بذبيحة الشكر', image: require('../assets/images/370.jpg'), music: require('../assets/music/370.jpg') },
  { title: '371. سوف أدخل أبوابك', image: require('../assets/images/371.jpg'), music: require('../assets/music/371.jpg') },
  { title: '372. شكرًا من كل القلب', image: require('../assets/images/372.jpg'), music: require('../assets/music/372.jpg') },
  { title: '373. الرب قد ملك', image: require('../assets/images/373.jpg'), music: require('../assets/music/373.jpg') },
  { title: '374. مستحق كل المجد يا يسوع', image: require('../assets/images/374.jpg'), music: require('../assets/music/374.jpg') },
  { title: '375. هل يستطيع الرب بي', image: require('../assets/images/375.jpg'), music: require('../assets/music/375.jpg') },
  { title: '376. نحن نعلن حضور يسوع', image: require('../assets/images/376.jpg'), music: require('../assets/music/376.jpg') },
  { title: '377. نسبح اسمك', image: require('../assets/images/377.jpg'), music: require('../assets/music/377.jpg') },
  { title: '378. ربي أنا عايز أرنم ليك', image: require('../assets/images/378.jpg'), music: require('../assets/music/378.jpg') },
  { title: '379. أيها الفخاري الأعظم', image: require('../assets/images/379.jpg'), music: require('../assets/music/379.jpg') },
  { title: '380. أوصنا أوصنا', image: require('../assets/images/380.jpg'), music: require('../assets/music/380.jpg') },
  { title: '381. ندخل ديارك', image: require('../assets/images/381.jpg'), music: require('../assets/music/381.jpg') },
  { title: '382. هيا نهتف أمام الرب', image: require('../assets/images/382.jpg'), music: require('../assets/music/382.jpg') },
  { title: '383. بشوق وحنين', image: require('../assets/images/383.jpg'), music: require('../assets/music/383.jpg') },
  { title: '384. رسالة أعطيتني', image: require('../assets/images/384.jpg'), music: require('../assets/music/384.jpg') },
  { title: '385. يسوع ملك الملوك', image: require('../assets/images/385.jpg'), music: require('../assets/music/385.jpg') },
  { title: '386. فوق كل قوة ورياسة', image: require('../assets/images/386.jpg'), music: require('../assets/music/386.jpg') },
  { title: '387. عظيم هو ربنا', image: require('../assets/images/387.jpg'), music: require('../assets/music/387.jpg') },
  { title: '388. روح الله ندعوك', image: require('../assets/images/388.jpg'), music: require('../assets/music/388.jpg') },
  { title: '389. نشيدي يعلو', image: require('../assets/images/389.jpg'), music: require('../assets/music/389.jpg') },
  { title: '390. هو الرب هو الرب', image: require('../assets/images/390.jpg'), music: require('../assets/music/390.jpg') },
  { title: '391. ربي نور بنورك في', image: require('../assets/images/391.jpg'), music: require('../assets/music/391.jpg') },
  { title: '392. الرب هو الله', image: require('../assets/images/392.jpg'), music: require('../assets/music/392.jpg') },
  { title: '393. أرفع يَدَاي عاليًا لله', image: require('../assets/images/393.jpg'), music: require('../assets/music/393.jpg') },
  { title: '394. ماران أث', image: require('../assets/images/394.jpg'), music: require('../assets/music/394.jpg') },
  { title: '395. محبة الله', image: require('../assets/images/395.jpg'), music: require('../assets/music/395.jpg') },
  { title: '396. خدامين تا يسو إيني في دنيا', image: require('../assets/images/396.jpg'), music: require('../assets/music/396.jpg') },
  { title: '397. فوق كلفاري في صليب', image: require('../assets/images/397.jpg'), music: require('../assets/music/397.jpg') },
  { title: '398. خلينا وري كلامات كلو', image: require('../assets/images/398.jpg'), music: require('../assets/music/398.jpg') },
  { title: '399. يسو بحبوني سيي', image: require('../assets/images/399.jpg'), music: require('../assets/music/399.jpg') },
  { title: '400. الاقو بتاي كلو', image: require('../assets/images/400.jpg'), music: require('../assets/music/400.jpg') },
  { title: '401. دكتور البتيمو سيي', image: require('../assets/images/401.jpg'), music: require('../assets/music/401.jpg') },
  { title: '402. عساكر كريستياني ماشي', image: require('../assets/images/402.jpg'), music: require('../assets/music/402.jpg') },
  { title: '403. ساعة تا صلاة', image: require('../assets/images/403.jpg'), music: require('../assets/music/403.jpg') },
  { title: '404. انت ماشي عشان صلي', image: require('../assets/images/404.jpg'), music: require('../assets/music/404.jpg') },
  { title: '405. اذا كان يسو يجي الليلة', image: require('../assets/images/405.jpg'), music: require('../assets/music/405.jpg') },
  { title: '406. اذا كان ألاقو مافيش لسة', image: require('../assets/images/406.jpg'), music: require('../assets/music/406.jpg') },
  { title: '407. موالاقو الدنيا كوري اسمع', image: require('../assets/images/407.jpg'), music: require('../assets/music/407.jpg') },
  { title: '408. سلطان يسو كريستو جورو', image: require('../assets/images/408.jpg'), music: require('../assets/music/408.jpg') },
  { title: '409. يسو كريستو مات في الصليب', image: require('../assets/images/409.jpg'), music: require('../assets/music/409.jpg') },
  { title: '410. كلامو اللي من كتاب', image: require('../assets/images/410.jpg'), music: require('../assets/music/410.jpg') },
  { title: '411. في حفرة ماليان مع دم', image: require('../assets/images/411.jpg'), music: require('../assets/music/411.jpg') },
  { title: '412. بلد اللي كويسي في فوق هناك', image: require('../assets/images/412.jpg'), music: require('../assets/music/412.jpg') },
  { title: '413. بالليل هادئ بالليل قدوس', image: require('../assets/images/413.jpg'), music: require('../assets/music/413.jpg') },
  { title: '414. اقيفو بقوة بتا ربونا', image: require('../assets/images/414.jpg'), music: require('../assets/music/414.jpg') },
  { title: '415. يسو كريستو بتيمو', image: require('../assets/images/415.jpg'), music: require('../assets/music/415.jpg') },
  { title: '416. اذا نينا نامشي مع يسو', image: require('../assets/images/416.jpg'), music: require('../assets/music/416.jpg') },
  { title: '417. رعاة كاني قي حارسو', image: require('../assets/images/417.jpg'), music: require('../assets/music/417.jpg') },
  { title: '418. تعالكم يا ناسي مع قليبة كلو', image: require('../assets/images/418.jpg'), music: require('../assets/music/418.jpg') },
  { title: '419. يسو قومو من القبر هللويا', image: require('../assets/images/419.jpg'), music: require('../assets/music/419.jpg') },
  { title: '420. يا ترى أي صديق', image: require('../assets/images/420.jpg'), music: require('../assets/music/420.jpg') },
  { title: '421. ما أعجب النعمة لي', image: require('../assets/images/421.jpg'), music: require('../assets/music/421.jpg') },
  { title: '422. خلني قرب الصليب', image: require('../assets/images/422.jpg'), music: require('../assets/music/422.jpg') },
  { title: '423. He is a miracle working God', image: require('../assets/images/423.jpg'), music: require('../assets/music/423.jpg') },
  { title: '424. You are the mighty God', image: require('../assets/images/424.jpg'), music: require('../assets/music/424.jpg') },
  { title: '425. Yesu ni wangu', image: require('../assets/images/425.jpg'), music: require('../assets/music/425.jpg') },
  { title: '426. Mambo sawa sawa', image: require('../assets/images/426.jpg'), music: require('../assets/music/426.jpg') },
  { title: '427. Winner', image: require('../assets/images/427.jpg'), music: require('../assets/music/427.jpg') },
  { title: '428. You are so mighty', image: require('../assets/images/428.jpg'), music: require('../assets/music/428.jpg') },
  { title: '429. Jesus is a mighty God', image: require('../assets/images/429.jpg'), music: require('../assets/music/429.jpg') },
  { title: '430. Yesu number one', image: require('../assets/images/430.jpg'), music: require('../assets/music/430.jpg') },
  { title: '431. Jesus on the inside (1)', image: require('../assets/images/431.jpg'), music: require('../assets/music/431.jpg') },
  { title: '432. Jesus on the inside (2)', image: require('../assets/images/432.jpg'), music: require('../assets/music/432.jpg') },
  { title: '433. Kum ba yah my Lord', image: require('../assets/images/433.jpg'), music: require('../assets/music/433.jpg') },
  { title: '434. Messiah is the King of kings', image: require('../assets/images/434.jpg'), music: require('../assets/music/434.jpg') },
  { title: '435. When Jesus says Yes', image: require('../assets/images/435.jpg'), music: require('../assets/music/435.jpg') },
  { title: '436. Jehovah, You are God', image: require('../assets/images/436.jpg'), music: require('../assets/music/436.jpg') },
  { title: '437. Our God is a wonderful God', image: require('../assets/images/437.jpg'), music: require('../assets/music/437.jpg') },
  { title: '438. You are Holy', image: require('../assets/images/438.jpg'), music: require('../assets/music/438.jpg') },
  { title: '439. We are serving the living God', image: require('../assets/images/439.jpg'), music: require('../assets/music/439.jpg') },
  { title: '440. Enter, rejoice and come in', image: require('../assets/images/440.jpg'), music: require('../assets/music/440.jpg') },
  { title: '441. Awesome God mighty God', image: require('../assets/images/441.jpg'), music: require('../assets/music/441.jpg') },
  { title: '442. Tambira Jehovah', image: require('../assets/images/442.jpg'), music: require('../assets/music/442.jpg') },
  { title: '443. There is no one like Jesus', image: require('../assets/images/443.jpg'), music: require('../assets/music/443.jpg') },
  { title: '444. There is something', image: require('../assets/images/444.jpg'), music: require('../assets/music/444.jpg') },
  { title: '445. Everybody praise the Lord now', image: require('../assets/images/445.jpg'), music: require('../assets/music/445.jpg') },
  { title: '446. My God is able', image: require('../assets/images/446.jpg'), music: require('../assets/music/446.jpg') },
  { title: '447. This is the day of joy', image: require('../assets/images/447.jpg'), music: require('../assets/music/447.jpg') },
  { title: '448. Come and reign', image: require('../assets/images/448.jpg'), music: require('../assets/music/448.jpg') },
  { title: '449. All other gods', image: require('../assets/images/449.jpg'), music: require('../assets/music/449.jpg') },
  { title: '450. We praise your name oh Lord', image: require('../assets/images/450.jpg'), music: require('../assets/music/450.jpg') },
  { title: '451. It’s a great thing to praise the Lord', image: require('../assets/images/451.jpg'), music: require('../assets/music/451.jpg') },
  { title: '452. I must be filled with the Holy Spirit', image: require('../assets/images/452.jpg'), music: require('../assets/music/452.jpg') },
  { title: '453. At the mention of your name', image: require('../assets/images/453.jpg'), music: require('../assets/music/453.jpg') },
  { title: '454. We are marching in the light of God', image: require('../assets/images/454.jpg'), music: require('../assets/music/454.jpg') },
  { title: '455. He is in control', image: require('../assets/images/455.jpg'), music: require('../assets/music/455.jpg') },
  { title: '456. Send your power', image: require('../assets/images/456.jpg'), music: require('../assets/music/456.jpg') },
  { title: '457. Thank you', image: require('../assets/images/457.jpg'), music: require('../assets/music/457.jpg') },
  { title: '458. This is the day', image: require('../assets/images/458.jpg'), music: require('../assets/music/458.jpg') },
  { title: '459. My God is so big', image: require('../assets/images/459.jpg'), music: require('../assets/music/459.jpg') },
  { title: '460. Praise Him', image: require('../assets/images/460.jpg'), music: require('../assets/music/460.jpg') },
  { title: '461. I have decided to follow Jesus', image: require('../assets/images/461.jpg'), music: require('../assets/music/461.jpg') },
  { title: '462. Music lesson (1) الدرس الأول', image: require('../assets/images/462.jpg'), music: require('../assets/music/462.jpg') },
  { title: '463. Music lesson (2) الدرس الثاني', image: require('../assets/images/463.jpg'), music: require('../assets/music/463.jpg') },
  { title: '464. Music lesson (3) الدرس الثالث', image: require('../assets/images/464.jpg'), music: require('../assets/music/464.jpg') },
  { title: '465. Music lesson (4) الدرس الرابع', image: require('../assets/images/465.jpg'), music: require('../assets/music/465.jpg') },
  { title: '466. Music lesson (5-1) الدرس الخامس', image: require('../assets/images/466.jpg'), music: require('../assets/music/466.jpg') },
  { title: '467. Music lesson (5-2) الدرس الخامس', image: require('../assets/images/467.jpg'), music: require('../assets/music/467.jpg') },
  { title: '468. Music lesson (6) الدرس السادس', image: require('../assets/images/468.jpg'), music: require('../assets/music/468.jpg') },
  { title: '469. Music lesson (7-1) الدرس السابع', image: require('../assets/images/469.jpg'), music: require('../assets/music/469.jpg') },
  { title: '470. Music lesson (7-2) الدرس السابع', image: require('../assets/images/470.jpg'), music: require('../assets/music/470.jpg') },
  { title: '471. Music lesson (7-3) الدرس السابع', image: require('../assets/images/471.jpg'), music: require('../assets/music/471.jpg') },
  { title: '472. Music lesson (8-1) الدرس الثامن', image: require('../assets/images/472.jpg'), music: require('../assets/music/472.jpg') },
  { title: '473. Music lesson (8-2) الدرس الثامن', image: require('../assets/images/473.jpg'), music: require('../assets/music/473.jpg') },
  { title: '474. Music lesson (9) الدرس التاسع', image: require('../assets/images/474.jpg'), music: require('../assets/music/474.jpg') },
  { title: '475. Music lesson (10) الجـيـتـار', image: require('../assets/images/475.jpg'), music: require('../assets/music/475.jpg') },
  { title: '476. Music lesson (11) كوردات الـجـيـتـار', image: require('../assets/images/476.jpg'), music: require('../assets/music/476.jpg') },
  { title: '477. Sudanese Hymnbook info', image: require('../assets/images/477.jpg'), music: require('../assets/music/477.jpg') },
];


  const ImageScreen = ({ route, navigation }) => {
    const { index } = route.params;
    const [scale, setScale] = useState(1);
    const [baseScale, setBaseScale] = useState(1);
    const swiperRef = useRef(null);
  
    const onPinchGestureEvent = ({ nativeEvent }) => {
      const newScale = baseScale * nativeEvent.scale;
      if (newScale < 1) {
        setScale(1);
      } else {
        setScale(newScale);
      }
    };
  
    const onPinchHandlerStateChange = ({ nativeEvent }) => {
      if (nativeEvent.oldState === 4) {
        setBaseScale(scale);
      }
    };
  
    const resetScale = () => {
      setScale(1);
      setBaseScale(1);
    };
  
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity style={styles.closeButton} onPress={() => navigation.goBack()}>
            <Icon name="times" size={25} color="#fff" />
          </TouchableOpacity>
        </View>
        <PinchGestureHandler onGestureEvent={onPinchGestureEvent} onHandlerStateChange={onPinchHandlerStateChange}>
          <View style={styles.imageContainer}>
            <Swiper
              ref={swiperRef}
              showsPagination
              loop={false}
              index={index}
              onIndexChanged={resetScale}
              containerStyle={styles.swiperContainer}
            >
              {data.map((item, index) => (
                <View style={styles.slide} key={index}>
                  <Image
                    source={item.image}
                    style={{ ...styles.image, width: '100%', height: '100%' }}
                    resizeMode="contain"
                  />
                </View>
              ))}
            </Swiper>
            <View style={styles.bottom}>
              <Text style={styles.bottomText}>Swipe down to close</Text>
            </View>
          </View>
        </PinchGestureHandler>
      </View>
    );
  };
  


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    paddingTop: 40,
    paddingBottom: 10,
    paddingHorizontal: 20,
  },
  closeButton: {
    marginRight: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  imageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  swiperContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  paginationStyle: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
  },
  dotStyle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  activeDotStyle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginHorizontal: 6,
    backgroundColor: '#fff',
  },
});

export default ImageScreen;